name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    env: 
      GOFLAGS: "-mod=vendor"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang: [1.13, 1.14, 1.15, 1.16]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.golang }}

    - name: Make go vet
      run: make vet

    - name: Unit Tests
      run: make test


    - name: Acceptance Tests 
      run: make testacc
      env:
        PAPERTRAIL_TOKEN: ${{ secrets.PAPERTRAIL_TOKEN }}

  build: 
    env: 
      GOFLAGS: "-mod=vendor"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Build on ${{ matrix.os}}_${{matrix.arch}}
      run: make build
      env: 
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        
